<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-18T15:25:01Z" name="Default suite" finished-at="2022-09-18T15:25:24Z" duration-ms="22838">
    <groups>
    </groups>
    <test started-at="2022-09-18T15:25:01Z" name="Default test" finished-at="2022-09-18T15:25:24Z" duration-ms="22838">
      <class name="testPack.TestClassB">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:testPack.TestClassB@63a65a25]" started-at="2022-09-18T20:55:01Z" name="beforeClass" finished-at="2022-09-18T20:55:15Z" duration-ms="14064" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="VerifyLoginPage()[pri:0, instance:testPack.TestClassB@63a65a25]" started-at="2022-09-18T20:55:15Z" name="VerifyLoginPage" finished-at="2022-09-18T20:55:22Z" duration-ms="7648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginPage -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testPack.TestClassB@63a65a25]" started-at="2022-09-18T20:55:22Z" name="afterMethod" finished-at="2022-09-18T20:55:23Z" duration-ms="683" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyLoginPage status=SUCCESS method=TestClassB.VerifyLoginPage()[pri:0, instance:testPack.TestClassB@63a65a25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="testA()[pri:0, instance:testPack.TestClassB@63a65a25]" started-at="2022-09-18T20:55:23Z" name="testA" finished-at="2022-09-18T20:55:23Z" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at testPack.TestClassB.testA(TestClassB.java:91)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testPack.TestClassB@63a65a25]" started-at="2022-09-18T20:55:23Z" name="afterMethod" finished-at="2022-09-18T20:55:24Z" duration-ms="403" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=TestClassB.testA()[pri:0, instance:testPack.TestClassB@63a65a25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testPack.TestClassB -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
